
package com.internetbanking.soap.SMS;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "Services", targetNamespace = "http://Services.laotel.com/", wsdlLocation = "file:/Users/thavisoukkhounlasapiphak/Desktop/ST/source_code/back-end/financal/src/main/resources/sendSMSService.wsdl")
public class Services
    extends Service
{

    private final static URL SERVICES_WSDL_LOCATION;
    private final static WebServiceException SERVICES_EXCEPTION;
    private final static QName SERVICES_QNAME = new QName("http://Services.laotel.com/", "Services");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/thavisoukkhounlasapiphak/Desktop/ST/source_code/back-end/financal/src/main/resources/sendSMSService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICES_WSDL_LOCATION = url;
        SERVICES_EXCEPTION = e;
    }

    public Services() {
        super(__getWsdlLocation(), SERVICES_QNAME);
    }

    public Services(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICES_QNAME, features);
    }

    public Services(URL wsdlLocation) {
        super(wsdlLocation, SERVICES_QNAME);
    }

    public Services(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICES_QNAME, features);
    }

    public Services(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Services(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicesSoap
     */
    @WebEndpoint(name = "ServicesSoap")
    public ServicesSoap getServicesSoap() {
        return super.getPort(new QName("http://Services.laotel.com/", "ServicesSoap"), ServicesSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicesSoap
     */
    @WebEndpoint(name = "ServicesSoap")
    public ServicesSoap getServicesSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://Services.laotel.com/", "ServicesSoap"), ServicesSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns ServicesSoap
     */
    @WebEndpoint(name = "ServicesSoap12")
    public ServicesSoap getServicesSoap12() {
        return super.getPort(new QName("http://Services.laotel.com/", "ServicesSoap12"), ServicesSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicesSoap
     */
    @WebEndpoint(name = "ServicesSoap12")
    public ServicesSoap getServicesSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://Services.laotel.com/", "ServicesSoap12"), ServicesSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICES_EXCEPTION!= null) {
            throw SERVICES_EXCEPTION;
        }
        return SERVICES_WSDL_LOCATION;
    }

}
