
package com.internetbanking.soap.newmodel;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;


import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "FCUBSACService", targetNamespace = "http://FCUBSACService.types.ws.gw.fcubs.ofss.com", wsdlLocation = "file:/Users/thavisoukkhounlasapiphak/Downloads/soap/src/main/resources/accountService.wsdl")
public class FCUBSACService
    extends Service
{

    private final static URL FCUBSACSERVICE_WSDL_LOCATION;
    private final static WebServiceException FCUBSACSERVICE_EXCEPTION;
    private final static QName FCUBSACSERVICE_QNAME = new QName("http://FCUBSACService.types.ws.gw.fcubs.ofss.com", "FCUBSACService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/thavisoukkhounlasapiphak/Downloads/soap/src/main/resources/accountService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FCUBSACSERVICE_WSDL_LOCATION = url;
        FCUBSACSERVICE_EXCEPTION = e;
    }

    public FCUBSACService() {
        super(__getWsdlLocation(), FCUBSACSERVICE_QNAME);
    }

    public FCUBSACService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FCUBSACSERVICE_QNAME, features);
    }

    public FCUBSACService(URL wsdlLocation) {
        super(wsdlLocation, FCUBSACSERVICE_QNAME);
    }

    public FCUBSACService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FCUBSACSERVICE_QNAME, features);
    }

    public FCUBSACService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FCUBSACService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FCUBSACServiceSEI
     */
    @WebEndpoint(name = "FCUBSACServiceSEI")
    public FCUBSACServiceSEI getFCUBSACServiceSEI() {
        return super.getPort(new QName("http://FCUBSACService.types.ws.gw.fcubs.ofss.com", "FCUBSACServiceSEI"), FCUBSACServiceSEI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FCUBSACServiceSEI
     */
    @WebEndpoint(name = "FCUBSACServiceSEI")
    public FCUBSACServiceSEI getFCUBSACServiceSEI(WebServiceFeature... features) {
        return super.getPort(new QName("http://FCUBSACService.types.ws.gw.fcubs.ofss.com", "FCUBSACServiceSEI"), FCUBSACServiceSEI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FCUBSACSERVICE_EXCEPTION!= null) {
            throw FCUBSACSERVICE_EXCEPTION;
        }
        return FCUBSACSERVICE_WSDL_LOCATION;
    }

}
