
package com.internetbanking.soap.newmodel;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "FCUBSACServiceSEI", targetNamespace = "http://FCUBSACService.types.ws.gw.fcubs.ofss.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FCUBSACServiceSEI {


    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.example.soap.newmodel.CREATEMJRNLAUTHFSFSRES
     */
    @WebMethod(operationName = "CreateMjrnlAuthFS")
    @WebResult(name = "CREATEMJRNLAUTH_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSACService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSACService.types.ws.gw.fcubs.ofss.com/FCUBSACServiceSEI/CreateMjrnlAuthFSRequest", output = "http://FCUBSACService.types.ws.gw.fcubs.ofss.com/FCUBSACServiceSEI/CreateMjrnlAuthFSResponse")
    public CREATEMJRNLAUTHFSFSRES createMjrnlAuthFS(
        @WebParam(name = "CREATEMJRNLAUTH_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSACService", partName = "RequestMsg")
        CREATEMJRNLAUTHFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.example.soap.newmodel.CREATEMJRNLAUTHIOPKRES
     */
    @WebMethod(operationName = "CreateMjrnlAuthIO")
    @WebResult(name = "CREATEMJRNLAUTH_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSACService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSACService.types.ws.gw.fcubs.ofss.com/FCUBSACServiceSEI/CreateMjrnlAuthIORequest", output = "http://FCUBSACService.types.ws.gw.fcubs.ofss.com/FCUBSACServiceSEI/CreateMjrnlAuthIOResponse")
    public CREATEMJRNLAUTHIOPKRES createMjrnlAuthIO(
        @WebParam(name = "CREATEMJRNLAUTH_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSACService", partName = "RequestMsg")
        CREATEMJRNLAUTHIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.example.soap.newmodel.MODIFYMJRNLAUTHFSFSRES
     */
    @WebMethod(operationName = "ModifyMjrnlAuthFS")
    @WebResult(name = "MODIFYMJRNLAUTH_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSACService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSACService.types.ws.gw.fcubs.ofss.com/FCUBSACServiceSEI/ModifyMjrnlAuthFSRequest", output = "http://FCUBSACService.types.ws.gw.fcubs.ofss.com/FCUBSACServiceSEI/ModifyMjrnlAuthFSResponse")
    public MODIFYMJRNLAUTHFSFSRES modifyMjrnlAuthFS(
        @WebParam(name = "MODIFYMJRNLAUTH_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSACService", partName = "RequestMsg")
        MODIFYMJRNLAUTHFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.example.soap.newmodel.MODIFYMJRNLAUTHIOPKRES
     */
    @WebMethod(operationName = "ModifyMjrnlAuthIO")
    @WebResult(name = "MODIFYMJRNLAUTH_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSACService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSACService.types.ws.gw.fcubs.ofss.com/FCUBSACServiceSEI/ModifyMjrnlAuthIORequest", output = "http://FCUBSACService.types.ws.gw.fcubs.ofss.com/FCUBSACServiceSEI/ModifyMjrnlAuthIOResponse")
    public MODIFYMJRNLAUTHIOPKRES modifyMjrnlAuthIO(
        @WebParam(name = "MODIFYMJRNLAUTH_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSACService", partName = "RequestMsg")
        MODIFYMJRNLAUTHIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.example.soap.newmodel.QUERYACCTRNSIOFSRES
     */
    @WebMethod(operationName = "QueryAccTrnsIO")
    @WebResult(name = "QUERYACCTRNS_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSACService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSACService.types.ws.gw.fcubs.ofss.com/FCUBSACServiceSEI/QueryAccTrnsIORequest", output = "http://FCUBSACService.types.ws.gw.fcubs.ofss.com/FCUBSACServiceSEI/QueryAccTrnsIOResponse")
    public QUERYACCTRNSIOFSRES queryAccTrnsIO(
        @WebParam(name = "QUERYACCTRNS_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSACService", partName = "RequestMsg")
        QUERYACCTRNSIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.example.soap.newmodel.QUERYAUDITTRAILIOFSRES
     */
    @WebMethod(operationName = "QueryAudittrailIO")
    @WebResult(name = "QUERYAUDITTRAIL_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSACService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSACService.types.ws.gw.fcubs.ofss.com/FCUBSACServiceSEI/QueryAudittrailIORequest", output = "http://FCUBSACService.types.ws.gw.fcubs.ofss.com/FCUBSACServiceSEI/QueryAudittrailIOResponse")
    public QUERYAUDITTRAILIOFSRES queryAudittrailIO(
        @WebParam(name = "QUERYAUDITTRAIL_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSACService", partName = "RequestMsg")
        QUERYAUDITTRAILIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.example.soap.newmodel.QUERYCUSTACTRNIOFSRES
     */
    @WebMethod(operationName = "QueryCustAcTrnIO")
    @WebResult(name = "QUERYCUSTACTRN_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSACService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSACService.types.ws.gw.fcubs.ofss.com/FCUBSACServiceSEI/QueryCustAcTrnIORequest", output = "http://FCUBSACService.types.ws.gw.fcubs.ofss.com/FCUBSACServiceSEI/QueryCustAcTrnIOResponse")
    public QUERYCUSTACTRNIOFSRES queryCustAcTrnIO(
        @WebParam(name = "QUERYCUSTACTRN_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSACService", partName = "RequestMsg")
        QUERYCUSTACTRNIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.example.soap.newmodel.QUERYCUSTOMERSTATIOFSRES
     */
    @WebMethod(operationName = "QueryCustomerStatIO")
    @WebResult(name = "QUERYCUSTOMERSTAT_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSACService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSACService.types.ws.gw.fcubs.ofss.com/FCUBSACServiceSEI/QueryCustomerStatIORequest", output = "http://FCUBSACService.types.ws.gw.fcubs.ofss.com/FCUBSACServiceSEI/QueryCustomerStatIOResponse")
    public QUERYCUSTOMERSTATIOFSRES queryCustomerStatIO(
        @WebParam(name = "QUERYCUSTOMERSTAT_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSACService", partName = "RequestMsg")
        QUERYCUSTOMERSTATIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.example.soap.newmodel.QUERYINTBRANCHPARAMIOFSRES
     */
    @WebMethod(operationName = "QueryIntBranchParamIO")
    @WebResult(name = "QUERYINTBRANCHPARAM_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSACService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSACService.types.ws.gw.fcubs.ofss.com/FCUBSACServiceSEI/QueryIntBranchParamIORequest", output = "http://FCUBSACService.types.ws.gw.fcubs.ofss.com/FCUBSACServiceSEI/QueryIntBranchParamIOResponse")
    public QUERYINTBRANCHPARAMIOFSRES queryIntBranchParamIO(
        @WebParam(name = "QUERYINTBRANCHPARAM_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSACService", partName = "RequestMsg")
        QUERYINTBRANCHPARAMIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.example.soap.newmodel.QUERYMJRNLAUTHIOFSRES
     */
    @WebMethod(operationName = "QueryMjrnlAuthIO")
    @WebResult(name = "QUERYMJRNLAUTH_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSACService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSACService.types.ws.gw.fcubs.ofss.com/FCUBSACServiceSEI/QueryMjrnlAuthIORequest", output = "http://FCUBSACService.types.ws.gw.fcubs.ofss.com/FCUBSACServiceSEI/QueryMjrnlAuthIOResponse")
    public QUERYMJRNLAUTHIOFSRES queryMjrnlAuthIO(
        @WebParam(name = "QUERYMJRNLAUTH_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSACService", partName = "RequestMsg")
        QUERYMJRNLAUTHIOFSREQ requestMsg);

}
