package com.internetbanking.soap.model.TransferRes;

import lombok.Data;

import java.util.ArrayList;

@Data
public class ContractDetailsFull {
    private String contrefno;
    private String prod;
    private String userrefno = null;
    private String dbtacc;
    private String cracc;
    private String drvaldt;
    private String crbrn;
    private String crccy;
    private float cramt;
    private String crvaldt;
    private float exgrate;
    private String dbtbrn;
    private String drccy;
    private float dramount;
    private String spreadcd;
    private float amtsttlacy;
    private String mckno = null;
    private String checknumber = null;
    private String chrgbearer;
    private String rtcd;
    private String rtpickdt;
    private String msgcd;
    private String msgdt;
    private String sourcerefno = null;
    private String sourcecd;
    private String acctingasof;
    private String accountingdate;
    private String multcusttrnasf;
    private String consolidatedacrefno = null;
    private String multicreditrefno = null;
    private String consolstat = null;
    private String proddesc;
    private String txntypecd = null;
    private String ourcorrespreq = null;
    private String receiver = null;
    private String awi = null;
    private String messageref = null;
    private String awi5 = null;
    private String awi6 = null;
    private String ultiben6;
    private String extdealrf = null;
    private String deliveryadd1 = null;
    private String deliveryadd2 = null;
    private String deliveryadd3 = null;
    private String deliveryadd4 = null;
    private String overoverdrft;
    private String paymentdet1 = null;
    private String paymentdet2 = null;
    private String paymentdet3 = null;
    private String paymentdet4 = null;
    private String byorderof1;
    private String byorderof2;
    private String byorderof3 = null;
    private String byorderof4 = null;
    private String ultben1;
    private String ultben2;
    private String ultben3 = null;
    private String ultben4 = null;
    private String byorderof5 = null;
    private String ultben5 = null;
    private String custspread = null;
    private String spreaddefn = null;
    private String awi2 = null;
    private String awi3 = null;
    private String awi4 = null;
    private String maker;
    private String makdttime;
    private String chkr;
    private String chkdttime;
    private String authstat;
    private String processtat;
    private String byorderof6 = null;
    private String intrmks = null;
    private String remitmsg;
    private String craccdesc;
    private String draccdesc;
    private String rtrefrs;
    private String upld = null;
    private String faxnumber = null;
    private String mobno = null;
    private String emailid = null;
    private String regrep1 = null;
    private String regrep2 = null;
    private String regrep3 = null;
    private String envcontent1 = null;
    private String envcontent2 = null;
    private String envcontent3 = null;
    private String envcontent4 = null;
    private String envcontent5 = null;
    private String socialsecno = null;
    private String deliverymode = null;
    private String rateref = null;
    private String ratedate = null;
    private String rateserial = null;
    private String streceiver = null;
    private String streminst = null;
    private String strecorresp = null;
    private String stintrmed = null;
    private String stacwtinst = null;
    private String stcorresp = null;
    private String stultben;
    private String stordcust;
    private String stourselves;
    private String ratetype;
    private float baserate;
    private String bookdt;
    private float verno;
    private float latverno;
    private String bankopercd;
    private String instrcd = null;
    private String extdealrfno = null;
    private String crsprddt;
    private String drsprddt;
    private String drspread;
    private String crspread;
    private String usrref = null;
    private String prdcd;
    private String cpty;
    private String modcd;
    private String conccy;
    private String source;
    private String txnstat;
    private String onceauth;
    private String consoldebitreferenceno = null;
    private String uniqueendtoendtxnref = null;
    private String referenceno = null;
    private String tag79NARRATIVE = null;
    CustCoverDetails CustCoverDetailsObject;
    StopPayment StopPaymentObject;
    private String notifErrLog = null;
    Taxes TaxesObject;
    ArrayList<Object> txnudfdetails = new ArrayList<Object>();
    Misdetails MisdetailsObject;
    ExtsysWsMaster ExtsysWsMasterObject;
    Settlements SettlementsObject;
    Advices AdvicesObject;
    private String prjdet = null;
    Charges ChargesObject;
    Chgclmdet ChgclmdetObject;

}
