package com.internetbanking.soap.model.TransferRes;

import lombok.Data;

import java.util.ArrayList;

@Data
public class Misdetails {
    private String conrefno;
    private String misgrp = null;
    private String relacc = null;
    private String reletedreference = null;
    private String mishead = null;
    private String rateflg;
    private String poolcd = null;
    private String refinancerate = null;
    private String refratetyp = null;
    private String calcmeth1 = null;
    private String refspread = null;
    private String refratecd = null;
    private String costcd1 = null;
    private String costcd2 = null;
    private String costcd3 = null;
    private String costcd4 = null;
    private String costcd5 = null;
    private String txnmis1 = null;
    private String txnmis10 = null;
    private String txnmis2 = null;
    private String txnmis3 = null;
    private String txnmis4 = null;
    private String txnmis5 = null;
    private String txnmis6 = null;
    private String txnmis7 = null;
    private String txnmis8 = null;
    private String txnmis9 = null;
    private String misgrpcomp = null;
    private String misgrptxn = null;
    private String compmis1 = null;
    private String compmis10 = null;
    private String compmis2 = null;
    private String compmis3 = null;
    private String compmis4 = null;
    private String compmis5 = null;
    private String compmis6 = null;
    private String compmis7 = null;
    private String compmis8 = null;
    private String compmis9 = null;
    private String fundmis1 = null;
    private String fundmis10 = null;
    private String fundmis2 = null;
    private String fundmis3 = null;
    private String fundmis4 = null;
    private String fundmis5 = null;
    private String fundmis6 = null;
    private String fundmis7 = null;
    private String fundmis8 = null;
    private String fundmis9 = null;
    private String misgrpfun = null;
    private String tranmis1;
    private String tranmis2 = null;
    private String tranmis3 = null;
    private String tranmis4 = null;
    private String tranmis5 = null;
    private String tranmis6 = null;
    private String tranmis7 = null;
    private String tranmis8 = null;
    private String tranmis9 = null;
    private String tranmis10 = null;
    private String commis1;
    private String commis2 = null;
    private String commis3 = null;
    private String commis4 = null;
    private String commis5 = null;
    private String commis6 = null;
    private String commis7 = null;
    private String commis8 = null;
    private String commis9 = null;
    private String commis10 = null;
    private String funmis1;
    private String funmis2 = null;
    private String funmis3 = null;
    private String funmis4 = null;
    private String funmis5 = null;
    private String funmis6 = null;
    private String funmis7 = null;
    private String funmis8 = null;
    private String funmis9 = null;
    private String funmis10 = null;
    ArrayList<Object> txnmisdetails = new ArrayList<Object>();
    ArrayList<Object> compmisdetails = new ArrayList<Object>();
    ArrayList<Object> fundmisdetails = new ArrayList<Object>();
    private String control = null;
    ArrayList<Object> balanceTrnsferLogDetails = new ArrayList<Object>();
}
