
package com.internetbanking.soap.transfer;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "FCUBSFTService", targetNamespace = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com", wsdlLocation = "file:/Users/thavisoukkhounlasapiphak/Downloads/soap/src/main/resources/transaction.wsdl")
public class FCUBSFTService
    extends Service
{

    private final static URL FCUBSFTSERVICE_WSDL_LOCATION;
    private final static WebServiceException FCUBSFTSERVICE_EXCEPTION;
    private final static QName FCUBSFTSERVICE_QNAME = new QName("http://FCUBSFTService.types.ws.gw.fcubs.ofss.com", "FCUBSFTService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/thavisoukkhounlasapiphak/Downloads/soap/src/main/resources/transaction.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FCUBSFTSERVICE_WSDL_LOCATION = url;
        FCUBSFTSERVICE_EXCEPTION = e;
    }

    public FCUBSFTService() {
        super(__getWsdlLocation(), FCUBSFTSERVICE_QNAME);
    }

    public FCUBSFTService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FCUBSFTSERVICE_QNAME, features);
    }

    public FCUBSFTService(URL wsdlLocation) {
        super(wsdlLocation, FCUBSFTSERVICE_QNAME);
    }

    public FCUBSFTService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FCUBSFTSERVICE_QNAME, features);
    }

    public FCUBSFTService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FCUBSFTService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FCUBSFTServiceSEI
     */
    @WebEndpoint(name = "FCUBSFTServiceSEI")
    public FCUBSFTServiceSEI getFCUBSFTServiceSEI() {
        return super.getPort(new QName("http://FCUBSFTService.types.ws.gw.fcubs.ofss.com", "FCUBSFTServiceSEI"), FCUBSFTServiceSEI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FCUBSFTServiceSEI
     */
    @WebEndpoint(name = "FCUBSFTServiceSEI")
    public FCUBSFTServiceSEI getFCUBSFTServiceSEI(WebServiceFeature... features) {
        return super.getPort(new QName("http://FCUBSFTService.types.ws.gw.fcubs.ofss.com", "FCUBSFTServiceSEI"), FCUBSFTServiceSEI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FCUBSFTSERVICE_EXCEPTION!= null) {
            throw FCUBSFTSERVICE_EXCEPTION;
        }
        return FCUBSFTSERVICE_WSDL_LOCATION;
    }

}
