
package com.internetbanking.soap.transfer;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "FCUBSFTServiceSEI", targetNamespace = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FCUBSFTServiceSEI {


    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.internetbanking.soap.transfer.AUTHORIZECONTRACTFSFSRES
     */
    @WebMethod(operationName = "AuthorizeContractFS")
    @WebResult(name = "AUTHORIZECONTRACT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/AuthorizeContractFSRequest", output = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/AuthorizeContractFSResponse")
    public AUTHORIZECONTRACTFSFSRES authorizeContractFS(
        @WebParam(name = "AUTHORIZECONTRACT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "RequestMsg")
        AUTHORIZECONTRACTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.internetbanking.soap.transfer.AUTHORIZECONTRACTIOPKRES
     */
    @WebMethod(operationName = "AuthorizeContractIO")
    @WebResult(name = "AUTHORIZECONTRACT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/AuthorizeContractIORequest", output = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/AuthorizeContractIOResponse")
    public AUTHORIZECONTRACTIOPKRES authorizeContractIO(
        @WebParam(name = "AUTHORIZECONTRACT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "RequestMsg")
        AUTHORIZECONTRACTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.internetbanking.soap.transfer.AUTHORIZEMT101FSFSRES
     */
    @WebMethod(operationName = "AuthorizeMT101FS")
    @WebResult(name = "AUTHORIZEMT101_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/AuthorizeMT101FSRequest", output = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/AuthorizeMT101FSResponse")
    public AUTHORIZEMT101FSFSRES authorizeMT101FS(
        @WebParam(name = "AUTHORIZEMT101_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "RequestMsg")
        AUTHORIZEMT101FSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.internetbanking.soap.transfer.AUTHORIZEMT101IOPKRES
     */
    @WebMethod(operationName = "AuthorizeMT101IO")
    @WebResult(name = "AUTHORIZEMT101_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/AuthorizeMT101IORequest", output = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/AuthorizeMT101IOResponse")
    public AUTHORIZEMT101IOPKRES authorizeMT101IO(
        @WebParam(name = "AUTHORIZEMT101_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "RequestMsg")
        AUTHORIZEMT101IOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.internetbanking.soap.transfer.AUTHORIZEPRODUCTFSFSRES
     */
    @WebMethod(operationName = "AuthorizeProductFS")
    @WebResult(name = "AUTHORIZEPRODUCT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/AuthorizeProductFSRequest", output = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/AuthorizeProductFSResponse")
    public AUTHORIZEPRODUCTFSFSRES authorizeProductFS(
        @WebParam(name = "AUTHORIZEPRODUCT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "RequestMsg")
        AUTHORIZEPRODUCTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.internetbanking.soap.transfer.AUTHORIZEPRODUCTIOPKRES
     */
    @WebMethod(operationName = "AuthorizeProductIO")
    @WebResult(name = "AUTHORIZEPRODUCT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/AuthorizeProductIORequest", output = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/AuthorizeProductIOResponse")
    public AUTHORIZEPRODUCTIOPKRES authorizeProductIO(
        @WebParam(name = "AUTHORIZEPRODUCT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "RequestMsg")
        AUTHORIZEPRODUCTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.internetbanking.soap.transfer.CLOSECONTRACTFSFSRES
     */
    @WebMethod(operationName = "CloseContractFS")
    @WebResult(name = "CLOSECONTRACT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/CloseContractFSRequest", output = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/CloseContractFSResponse")
    public CLOSECONTRACTFSFSRES closeContractFS(
        @WebParam(name = "CLOSECONTRACT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "RequestMsg")
        CLOSECONTRACTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.internetbanking.soap.transfer.CLOSECONTRACTIOPKRES
     */
    @WebMethod(operationName = "CloseContractIO")
    @WebResult(name = "CLOSECONTRACT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/CloseContractIORequest", output = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/CloseContractIOResponse")
    public CLOSECONTRACTIOPKRES closeContractIO(
        @WebParam(name = "CLOSECONTRACT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "RequestMsg")
        CLOSECONTRACTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.internetbanking.soap.transfer.CLOSEPRODUCTFSFSRES
     */
    @WebMethod(operationName = "CloseProductFS")
    @WebResult(name = "CLOSEPRODUCT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/CloseProductFSRequest", output = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/CloseProductFSResponse")
    public CLOSEPRODUCTFSFSRES closeProductFS(
        @WebParam(name = "CLOSEPRODUCT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "RequestMsg")
        CLOSEPRODUCTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.internetbanking.soap.transfer.CLOSEPRODUCTIOPKRES
     */
    @WebMethod(operationName = "CloseProductIO")
    @WebResult(name = "CLOSEPRODUCT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/CloseProductIORequest", output = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/CloseProductIOResponse")
    public CLOSEPRODUCTIOPKRES closeProductIO(
        @WebParam(name = "CLOSEPRODUCT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "RequestMsg")
        CLOSEPRODUCTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.internetbanking.soap.transfer.CREATECONTRACTFSFSRES
     */
    @WebMethod(operationName = "CreateContractFS")
    @WebResult(name = "CREATECONTRACT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/CreateContractFSRequest", output = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/CreateContractFSResponse")
    public CREATECONTRACTFSFSRES createContractFS(
        @WebParam(name = "CREATECONTRACT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "RequestMsg")
        CREATECONTRACTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.internetbanking.soap.transfer.CREATECONTRACTIOPKRES
     */
    @WebMethod(operationName = "CreateContractIO")
    @WebResult(name = "CREATECONTRACT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/CreateContractIORequest", output = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/CreateContractIOResponse")
    public CREATECONTRACTIOPKRES createContractIO(
        @WebParam(name = "CREATECONTRACT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "RequestMsg")
        CREATECONTRACTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.internetbanking.soap.transfer.CREATEMT101FSFSRES
     */
    @WebMethod(operationName = "CreateMT101FS")
    @WebResult(name = "CREATEMT101_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/CreateMT101FSRequest", output = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/CreateMT101FSResponse")
    public CREATEMT101FSFSRES createMT101FS(
        @WebParam(name = "CREATEMT101_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "RequestMsg")
        CREATEMT101FSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.internetbanking.soap.transfer.CREATEMT101IOPKRES
     */
    @WebMethod(operationName = "CreateMT101IO")
    @WebResult(name = "CREATEMT101_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/CreateMT101IORequest", output = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/CreateMT101IOResponse")
    public CREATEMT101IOPKRES createMT101IO(
        @WebParam(name = "CREATEMT101_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "RequestMsg")
        CREATEMT101IOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.internetbanking.soap.transfer.CREATEPRODUCTFSFSRES
     */
    @WebMethod(operationName = "CreateProductFS")
    @WebResult(name = "CREATEPRODUCT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/CreateProductFSRequest", output = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/CreateProductFSResponse")
    public CREATEPRODUCTFSFSRES createProductFS(
        @WebParam(name = "CREATEPRODUCT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "RequestMsg")
        CREATEPRODUCTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.internetbanking.soap.transfer.CREATEPRODUCTIOPKRES
     */
    @WebMethod(operationName = "CreateProductIO")
    @WebResult(name = "CREATEPRODUCT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/CreateProductIORequest", output = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/CreateProductIOResponse")
    public CREATEPRODUCTIOPKRES createProductIO(
        @WebParam(name = "CREATEPRODUCT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "RequestMsg")
        CREATEPRODUCTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.internetbanking.soap.transfer.DELETECONTRACTFSFSRES
     */
    @WebMethod(operationName = "DeleteContractFS")
    @WebResult(name = "DELETECONTRACT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/DeleteContractFSRequest", output = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/DeleteContractFSResponse")
    public DELETECONTRACTFSFSRES deleteContractFS(
        @WebParam(name = "DELETECONTRACT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "RequestMsg")
        DELETECONTRACTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.internetbanking.soap.transfer.DELETECONTRACTIOPKRES
     */
    @WebMethod(operationName = "DeleteContractIO")
    @WebResult(name = "DELETECONTRACT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/DeleteContractIORequest", output = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/DeleteContractIOResponse")
    public DELETECONTRACTIOPKRES deleteContractIO(
        @WebParam(name = "DELETECONTRACT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "RequestMsg")
        DELETECONTRACTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.internetbanking.soap.transfer.DELETEMT101FSFSRES
     */
    @WebMethod(operationName = "DeleteMT101FS")
    @WebResult(name = "DELETEMT101_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/DeleteMT101FSRequest", output = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/DeleteMT101FSResponse")
    public DELETEMT101FSFSRES deleteMT101FS(
        @WebParam(name = "DELETEMT101_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "RequestMsg")
        DELETEMT101FSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.internetbanking.soap.transfer.DELETEMT101IOPKRES
     */
    @WebMethod(operationName = "DeleteMT101IO")
    @WebResult(name = "DELETEMT101_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/DeleteMT101IORequest", output = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/DeleteMT101IOResponse")
    public DELETEMT101IOPKRES deleteMT101IO(
        @WebParam(name = "DELETEMT101_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "RequestMsg")
        DELETEMT101IOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.internetbanking.soap.transfer.DELETEPRODUCTFSFSRES
     */
    @WebMethod(operationName = "DeleteProductFS")
    @WebResult(name = "DELETEPRODUCT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/DeleteProductFSRequest", output = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/DeleteProductFSResponse")
    public DELETEPRODUCTFSFSRES deleteProductFS(
        @WebParam(name = "DELETEPRODUCT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "RequestMsg")
        DELETEPRODUCTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.internetbanking.soap.transfer.DELETEPRODUCTIOPKRES
     */
    @WebMethod(operationName = "DeleteProductIO")
    @WebResult(name = "DELETEPRODUCT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/DeleteProductIORequest", output = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/DeleteProductIOResponse")
    public DELETEPRODUCTIOPKRES deleteProductIO(
        @WebParam(name = "DELETEPRODUCT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "RequestMsg")
        DELETEPRODUCTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.internetbanking.soap.transfer.LIQUIDATECONTRACTFSFSRES
     */
    @WebMethod(operationName = "LiquidateContractFS")
    @WebResult(name = "LIQUIDATECONTRACT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/LiquidateContractFSRequest", output = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/LiquidateContractFSResponse")
    public LIQUIDATECONTRACTFSFSRES liquidateContractFS(
        @WebParam(name = "LIQUIDATECONTRACT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "RequestMsg")
        LIQUIDATECONTRACTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.internetbanking.soap.transfer.LIQUIDATECONTRACTIOPKRES
     */
    @WebMethod(operationName = "LiquidateContractIO")
    @WebResult(name = "LIQUIDATECONTRACT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/LiquidateContractIORequest", output = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/LiquidateContractIOResponse")
    public LIQUIDATECONTRACTIOPKRES liquidateContractIO(
        @WebParam(name = "LIQUIDATECONTRACT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "RequestMsg")
        LIQUIDATECONTRACTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.internetbanking.soap.transfer.MODIFYCONTRACTFSFSRES
     */
    @WebMethod(operationName = "ModifyContractFS")
    @WebResult(name = "MODIFYCONTRACT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/ModifyContractFSRequest", output = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/ModifyContractFSResponse")
    public MODIFYCONTRACTFSFSRES modifyContractFS(
        @WebParam(name = "MODIFYCONTRACT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "RequestMsg")
        MODIFYCONTRACTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.internetbanking.soap.transfer.MODIFYCONTRACTIOPKRES
     */
    @WebMethod(operationName = "ModifyContractIO")
    @WebResult(name = "MODIFYCONTRACT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/ModifyContractIORequest", output = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/ModifyContractIOResponse")
    public MODIFYCONTRACTIOPKRES modifyContractIO(
        @WebParam(name = "MODIFYCONTRACT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "RequestMsg")
        MODIFYCONTRACTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.internetbanking.soap.transfer.MODIFYMT101FSFSRES
     */
    @WebMethod(operationName = "ModifyMT101FS")
    @WebResult(name = "MODIFYMT101_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/ModifyMT101FSRequest", output = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/ModifyMT101FSResponse")
    public MODIFYMT101FSFSRES modifyMT101FS(
        @WebParam(name = "MODIFYMT101_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "RequestMsg")
        MODIFYMT101FSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.internetbanking.soap.transfer.MODIFYMT101IOPKRES
     */
    @WebMethod(operationName = "ModifyMT101IO")
    @WebResult(name = "MODIFYMT101_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/ModifyMT101IORequest", output = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/ModifyMT101IOResponse")
    public MODIFYMT101IOPKRES modifyMT101IO(
        @WebParam(name = "MODIFYMT101_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "RequestMsg")
        MODIFYMT101IOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.internetbanking.soap.transfer.MODIFYPRODUCTFSFSRES
     */
    @WebMethod(operationName = "ModifyProductFS")
    @WebResult(name = "MODIFYPRODUCT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/ModifyProductFSRequest", output = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/ModifyProductFSResponse")
    public MODIFYPRODUCTFSFSRES modifyProductFS(
        @WebParam(name = "MODIFYPRODUCT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "RequestMsg")
        MODIFYPRODUCTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.internetbanking.soap.transfer.MODIFYPRODUCTIOPKRES
     */
    @WebMethod(operationName = "ModifyProductIO")
    @WebResult(name = "MODIFYPRODUCT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/ModifyProductIORequest", output = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/ModifyProductIOResponse")
    public MODIFYPRODUCTIOPKRES modifyProductIO(
        @WebParam(name = "MODIFYPRODUCT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "RequestMsg")
        MODIFYPRODUCTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.internetbanking.soap.transfer.QUERYCONTRACTIOFSRES
     */
    @WebMethod(operationName = "QueryContractIO")
    @WebResult(name = "QUERYCONTRACT_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/QueryContractIORequest", output = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/QueryContractIOResponse")
    public QUERYCONTRACTIOFSRES queryContractIO(
        @WebParam(name = "QUERYCONTRACT_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "RequestMsg")
        QUERYCONTRACTIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.internetbanking.soap.transfer.QUERYMT101IOFSRES
     */
    @WebMethod(operationName = "QueryMT101IO")
    @WebResult(name = "QUERYMT101_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/QueryMT101IORequest", output = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/QueryMT101IOResponse")
    public QUERYMT101IOFSRES queryMT101IO(
        @WebParam(name = "QUERYMT101_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "RequestMsg")
        QUERYMT101IOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.internetbanking.soap.transfer.QUERYPRODUCTIOFSRES
     */
    @WebMethod(operationName = "QueryProductIO")
    @WebResult(name = "QUERYPRODUCT_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/QueryProductIORequest", output = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/QueryProductIOResponse")
    public QUERYPRODUCTIOFSRES queryProductIO(
        @WebParam(name = "QUERYPRODUCT_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "RequestMsg")
        QUERYPRODUCTIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.internetbanking.soap.transfer.REOPENPRODUCTFSFSRES
     */
    @WebMethod(operationName = "ReopenProductFS")
    @WebResult(name = "REOPENPRODUCT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/ReopenProductFSRequest", output = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/ReopenProductFSResponse")
    public REOPENPRODUCTFSFSRES reopenProductFS(
        @WebParam(name = "REOPENPRODUCT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "RequestMsg")
        REOPENPRODUCTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.internetbanking.soap.transfer.REOPENPRODUCTIOPKRES
     */
    @WebMethod(operationName = "ReopenProductIO")
    @WebResult(name = "REOPENPRODUCT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/ReopenProductIORequest", output = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/ReopenProductIOResponse")
    public REOPENPRODUCTIOPKRES reopenProductIO(
        @WebParam(name = "REOPENPRODUCT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "RequestMsg")
        REOPENPRODUCTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.internetbanking.soap.transfer.REVERSECONTRACTFSFSRES
     */
    @WebMethod(operationName = "ReverseContractFS")
    @WebResult(name = "REVERSECONTRACT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/ReverseContractFSRequest", output = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/ReverseContractFSResponse")
    public REVERSECONTRACTFSFSRES reverseContractFS(
        @WebParam(name = "REVERSECONTRACT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "RequestMsg")
        REVERSECONTRACTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.internetbanking.soap.transfer.REVERSECONTRACTIOPKRES
     */
    @WebMethod(operationName = "ReverseContractIO")
    @WebResult(name = "REVERSECONTRACT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/ReverseContractIORequest", output = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/ReverseContractIOResponse")
    public REVERSECONTRACTIOPKRES reverseContractIO(
        @WebParam(name = "REVERSECONTRACT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "RequestMsg")
        REVERSECONTRACTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.internetbanking.soap.transfer.SUMMARYQUERYPRODUCTIOFSRES
     */
    @WebMethod(operationName = "SummaryQueryProductIO")
    @WebResult(name = "SUMMARYQUERYPRODUCT_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/SummaryQueryProductIORequest", output = "http://FCUBSFTService.types.ws.gw.fcubs.ofss.com/FCUBSFTServiceSEI/SummaryQueryProductIOResponse")
    public SUMMARYQUERYPRODUCTIOFSRES summaryQueryProductIO(
        @WebParam(name = "SUMMARYQUERYPRODUCT_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSFTService", partName = "RequestMsg")
        SUMMARYQUERYPRODUCTIOFSREQ requestMsg);

}
